# Generated by Django 2.2.9 on 2020-01-02 04:30

from django.db import migrations

def create_initial_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(username="steve")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
