# Generated by Django 2.2.9 on 2020-01-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_auto_20200102_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_list', models.TextField(null=True)),
                ('room_code', models.CharField(max_length=4)),
                ('game_started', models.BooleanField(default=True)),
                ('question_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.Question', verbose_name='Series')),
            ],
        ),
    ]
