# Generated by Django 2.2.9 on 2020-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200103_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_list',
        ),
        migrations.AddField(
            model_name='room',
            name='user_list',
            field=models.ManyToManyField(to='rooms.User'),
        ),
    ]
