# Generated by Django 2.2.9 on 2020-01-05 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200103_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_started',
        ),
        migrations.AddField(
            model_name='room',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=[], size=10),
        ),
        migrations.AddField(
            model_name='room',
            name='false_answer',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='user_with_false_question',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='vote_count_false',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='vote_count_true',
            field=models.IntegerField(default=0),
        ),
    ]
