# Generated by Django 2.2.9 on 2020-01-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200105_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='correct_answers',
            new_name='right_answers',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='users',
            new_name='user_count',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user_with_false_question',
            new_name='user_wrong',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='vote_count_false',
            new_name='vote_wrong',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='false_answer',
            new_name='wrong_answer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vote_count_true',
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default=[], max_length=20),
        ),
    ]
