# Generated by Django 2.2.9 on 2020-01-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200105_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(default='W', max_length=1),
        ),
    ]
