# Generated by Django 2.2.9 on 2020-01-06 00:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200105_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=20)),
                ('answer', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='room',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wrong_answer',
        ),
        migrations.AddField(
            model_name='room',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=',', max_length=220), default=[], size=10),
        ),
    ]
