# Generated by Django 2.2.9 on 2020-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200106_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
