# Generated by Django 2.2.9 on 2020-01-07 03:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200107_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='question_index_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=10),
        ),
    ]
