# Generated by Django 2.2.9 on 2020-01-07 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_question_index_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='question_index_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=10),
        ),
    ]
