# Generated by Django 2.2.9 on 2020-01-07 23:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200107_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10),
        ),
        migrations.AddField(
            model_name='room',
            name='voted_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=41), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=',', max_length=220), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='question_index_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=10),
        ),
    ]
