# Generated by Django 2.2.9 on 2020-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_room_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='caught',
            field=models.BooleanField(default=False),
        ),
    ]
