# Generated by Django 2.2.9 on 2020-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_room_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='winner_determined',
            field=models.BooleanField(default=False),
        ),
    ]
